CREATE SCHEMA pmm;

CREATE TABLE pmm.USER_STATUS (
    ID SERIAL PRIMARY KEY,
    DESCRIPTION VARCHAR(25) UNIQUE NOT NULL
);

CREATE TABLE pmm.USER_CREDENTIALS (
    ID SERIAL PRIMARY KEY,
    EMAIL VARCHAR(40) UNIQUE NOT NULL,
    PASSWORD VARCHAR(100),
    INTENTS INTEGER NULL,
    USER_STATUS_ID INTEGER REFERENCES USER_STATUS (ID)
);

INSERT INTO pmm.USER_SATUS (DESCRIPTION) VALUES ('created', 'available', 'disavailable', 'removed');

